cc.exports.CPGMenuCommand = import(".command.CPGMenuCommand")
cc.exports.CPActNotifyCommand = import(".command.CPActNotifyCommand")
cc.exports.CPActInfoCommand = import(".command.CPActInfoCommand")
cc.exports.CPGameStationCommand = import(".command.CPGameStationCommand")

cc.exports.CPEatReqCommand = import(".command.CPEatReqCommand")
cc.exports.CPPengReqCommand = import(".command.CPPengReqCommand")
cc.exports.CPGangReqCommand = import(".command.CPGangReqCommand")
cc.exports.CPHuReqCommand = import(".command.CPHuReqCommand")
cc.exports.CPPassReqCommand = import(".command.CPPassReqCommand")