
cc.exports.StartGameCommand = import(".command.StartGameCommand")
cc.exports.StartSceneCommand = import(".command.StartSceneCommand")
cc.exports.StartVoteCommand = import(".command.StartVoteCommand")

cc.exports.RequestPrivateConnectCommand = import(".command.RequestPrivateConnectCommand")
cc.exports.RequestPrivateRoomCommand = import(".command.RequestPrivateRoomCommand")
cc.exports.RequestPrivateSitCommand = import(".command.RequestPrivateSitCommand")
cc.exports.RequestPrivateLeaveCommand = import(".command.RequestPrivateLeaveCommand")
cc.exports.RequestPrivateDismissCommand = import(".command.RequestPrivateDismissCommand")
cc.exports.RequestStartVoteCommand = import(".command.RequestStartVoteCommand")
cc.exports.RequestVoteCommand = import(".command.RequestVoteCommand")

cc.exports.RequestQuickQueueCommand = import(".command.RequestQuickQueueCommand")
cc.exports.RequestQuickCancelQueueCommand = import(".command.RequestQuickCancelQueueCommand")
cc.exports.RequestQuickConnectCommand = import(".command.RequestQuickConnectCommand")
cc.exports.RequestQuickLeaveCommand = import(".command.RequestQuickLeaveCommand")

cc.exports.RequestCreateVideoCommand = import(".command.RequestCreateVideoCommand")
cc.exports.RequestFreeConnectCommand = import(".command.RequestFreeConnectCommand")
cc.exports.RequestFreeSitCommand = import(".command.RequestFreeSitCommand")
cc.exports.RequestFreeLeaveCommand = import(".command.RequestFreeLeaveCommand")
cc.exports.RequestJoinCptCommand = import(".command.RequestJoinCptCommand")
cc.exports.RequsetQuitCptCommand = import(".command.RequsetQuitCptCommand")
cc.exports.StartWaitRiseCommand = import(".command.StartWaitRiseCommand")
cc.exports.RequestEliminateCommand = import(".command.RequestEliminateCommand")
cc.exports.StartEliminateCommand = import(".command.StartEliminateCommand")
cc.exports.RequestJoinStateCommand = import(".command.RequestJoinStateCommand")