cc.exports.OutCardCommand = import(".command.OutCardCommand")
cc.exports.OCOutCardCommand = import(".command.OCOutCardCommand")
cc.exports.OCActNotifyCommand = import(".command.OCActNotifyCommand")
cc.exports.OCActInfoCommand = import(".command.OCActInfoCommand")
cc.exports.OCCurSameCardCommand = import(".command.OCCurSameCardCommand")
cc.exports.OCGameStationCommand = import(".command.OCGameStationCommand")