
cc.FileUtils:getInstance():addSearchPath("platform")

import(".extends")
import(".PlatformConstants")

import(".components.gamelist.init")
import(".components.hall.init")
import(".components.load.init")
import(".components.login.init")
import(".components.register.init")
import(".components.roomlist.init")
import(".components.privateroom.init")
import(".components.update.init")
import(".components.userinfo.init")
import(".components.network.init")
import(".components.horselamp.init")
import(".components.announce.init")
import(".components.bank.init")
import(".components.agreement.init")
import(".components.shop.init")
import(".components.benefits.init")
import(".components.lottery.init")
import(".components.realname.init")
import(".components.message.init")
import(".components.sysset.init")
import(".components.help.init")
import(".components.matchrecords.init")
import(".components.tasks.init")
import(".components.banginvitecode.init")
import(".components.competitionlist.init")
import(".components.club.init")

local platformFacade = cc.load("puremvc").Facade.getInstance("platform")
local PlatformConstants = cc.exports.PlatformConstants

platformFacade:registerCommand(PlatformConstants.START_MESSAGE, cc.exports.StartMessageCommand)
platformFacade:registerCommand(PlatformConstants.CREATE_MSGBOX, cc.exports.StartCreateMsgBoxCommand)
platformFacade:registerCommand(PlatformConstants.CREATE_LOADINGANIM, cc.exports.CreateLoadingAnimCommand)
platformFacade:registerCommand(PlatformConstants.START_LOAD, cc.exports.StartLoadCommand)
platformFacade:registerCommand(PlatformConstants.TEST_NETWORK, cc.exports.TestTcpCommand)
platformFacade:registerCommand(PlatformConstants.DOWNLOAD_HEAD, cc.exports.DownloadHeadCommand)
platformFacade:registerCommand(PlatformConstants.REQUEST_USERINFO, cc.exports.RequestUserInfoCommand)
platformFacade:registerCommand(PlatformConstants.UPDATE_USERWEALTH, cc.exports.UpdateUserWealthCommand)